mcreatorVersion=2026.2.33218
# Not for snapshots, for that edit build.gradle line 15 or directly plugin.json
pluginVersion=2026.2-2.7.4
mcVersion=26.1.2
# This is not the only reference for "26.1.2", you will need to change some others as well.
mcreator_path=unassigned
# To test the generator
# To see which branch the automatic tests run on, see test.yml line 29

# updateJSONURL will be mcVersion-mcreatorVersion (must match the branch name)