plugins {
    id 'net.fabricmc.fabric-loom' version '1.16-SNAPSHOT'
}

version = '1.0'
base.archivesName = "modid"

loom {
// The following code makes impossible to setup Gradle projects
//    mixin {
//        useLegacyMixinAp = true
//        defaultRefmapName = actualmodid + ".refmap.json"
//    }

    if (file("src/main/resources/META-INF/${modid}.classtweaker").exists())
        accessWidenerPath = file("src/main/resources/META-INF/${modid}.classtweaker")
}

dependencies {
    minecraft "com.mojang:minecraft:${generator.getGeneratorMinecraftVersion()}"
    implementation "net.fabricmc:fabric-loader:0.19.2"

    // Fabric API
    implementation "net.fabricmc.fabric-api:fabric-api:${generator.getGeneratorBuildFileVersion()}+${generator.getGeneratorMinecraftVersion()}"
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 25
}

java {
    withSourcesJar()
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

apply from: 'mcreator.gradle'