<#-- @formatter:off -->
/*
 *    MCreator note:
 *
 *    If you lock base mod element files, you can edit this file and the proxy files
 *    and they won't get overwritten. If you change your mod package or modid, you
 *    need to apply these changes to this file MANUALLY.
 *
 *
 *    Keep the ${JavaModName}Elements object in this class and all calls to this object
 *    INTACT in order to preserve functionality of mod elements generated by MCreator.
 *
 *    If you do not lock base mod element files in Workspace settings, this file
 *    will be REGENERATED on each build.
 *
 */

package ${package};

public class ${JavaModName} implements ModInitializer {

<#list w.getElementsOfType("ITEM") as item>
	public static final Item ${item} = new ${item}();
</#list>

<#list w.getElementsOfType("FOOD") as food>
	public static final Item ${food} = new ${food}();
</#list>

<#list w.getElementsOfType("BLOCK") as block>
    public static final Block ${block} = new ${block}();
</#list>

	@Override
	public void onInitialize() {
<#list w.getElementsOfType("ITEM") as item>
		Registry.register(Registry.ITEM, new Identifier("${modid}", "${item.getRegistryName()}"), ${item});
</#list>

<#list w.getElementsOfType("FOOD") as food>
		Registry.register(Registry.ITEM, new Identifier("${modid}", "${food.getRegistryName()}"), ${food});
</#list>

<#list w.getElementsOfType("TOOL") as tool>
		Registry.register(Registry.ITEM, new Identifier("${modid}", "${tool.getRegistryName()}"), new ${tool}Item(new ${tool}Material()));
</#list>

<#list w.getElementsOfType("BLOCK") as block>
		Registry.register(Registry.BLOCK, new Identifier("${modid}", "${block.getRegistryName()}"), ${block});
		Registry.register(Registry.ITEM, new Identifier("${modid}", "${block.getRegistryName()}"), new BlockItem(${block}, new Item.Settings().group(ItemGroup.BUILDING_BLOCKS)));
</#list>
	}
}
<#-- @formatter:on -->